import nextPlugin from "@next/eslint-plugin-next";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // convex/_generated is regenerated by `convex dev` on every push and a hand
    // edit to it is a bug, so it is configuration rather than suppression to
    // keep it out of lint. It legitimately contains `any` in its FilterApi types.
    ignores: [
      "node_modules",
      ".next",
      "out",
      "coverage",
      "next-env.d.ts",
      "**/*.config.*",
      "convex/_generated",
    ],
  },
  tseslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    plugins: {
      "@next/next": nextPlugin,
      "react-hooks": reactHooks,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
      ...reactHooks.configs.recommended.rules,
    },
  },
);
