export const DEVICES = [
  { id: "pc", label: "PC" },
  { id: "steam-deck", label: "Steam Deck" },
  { id: "rog-ally", label: "ROG Ally" },
  { id: "legion-go", label: "Legion Go" },
  { id: "mac", label: "Mac" },
  { id: "ps5", label: "PS5" },
  { id: "ps4", label: "PS4" },
  { id: "ps3", label: "PS3" },
  { id: "psp-vita", label: "PSP / Vita" },
  { id: "xbox-series", label: "Xbox Series" },
  { id: "xbox-one", label: "Xbox One" },
  { id: "xbox-360", label: "Xbox 360" },
  { id: "switch-2", label: "Switch 2" },
  { id: "switch", label: "Switch" },
  { id: "vr", label: "VR headset" },
  { id: "cloud", label: "Cloud" },
  { id: "mobile", label: "Mobile" },
] as const;
