export const STOREFRONTS = [
  { id: "steam", label: "Steam" },
  { id: "epic", label: "Epic" },
  { id: "gog", label: "GOG" },
  { id: "ubisoft", label: "Ubisoft Connect" },
  { id: "ea", label: "EA App" },
  { id: "battlenet", label: "Battle.net" },
  { id: "rockstar", label: "Rockstar" },
  { id: "microsoft", label: "Microsoft Store" },
  { id: "game-pass", label: "Game Pass" },
  { id: "ps-store", label: "PS Store" },
  { id: "ps-plus", label: "PS Plus" },
  { id: "eshop", label: "Nintendo eShop" },
  { id: "humble", label: "Humble" },
  { id: "itch", label: "itch.io" },
  { id: "amazon", label: "Amazon Games" },
  { id: "disc", label: "Physical disc" },
  { id: "other", label: "Other" },
] as const;
